# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d1e1a005265ea0f5cdcdeb017928da93f3e66680b8f6ba54a15746d799bd0c9132745aca6d5da9568aa30be893dc7045754e8191ef09c1300589117343dcff5

test:
  secret_key_base: 61986faf021fa7b8c0350c049b28458786abbfa534cefdeabf38a3ce6c37b50ea8cb71dad420a436fd1116869e2844fef15076d335ae8745fc331ec37d10eac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
